export const metadata = {
  title: "Next.js test",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
      >
        <header
          style={{ backgroundColor: "#000", color: "#fff", padding: "1rem" }}
        >
          <p>Header</p>
        </header>
        <main>{children}</main>
        <footer
          style={{
            backgroundColor: "#85be00",
            padding: "1rem",
            marginTop: "auto",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
